RX interruption catched
TASK_ALLOCATION_SEND
Got slot: 0 
Task total size (txt+bss): 3556 
Task addr: 2147523484 
Task slot: 0 
Task slot TaskAddr: 2147523484 
2NI_RX DONE!
RX interruption catched
TASK_ALLOCATION_FINISHED
SendingQueue_front: 0 
API_Try2Send success!
4NI_RX DONE!
TX interruption catched
API_Try2Send failed - empty SendQueue!
RX interruption catched
Chegou um TASK_START!
6NI_RX DONE!
RX interruption catched
Chegou um TASK_RUN!
Starting Task 0  from app 1 
taskSlot run: 0 
7NI_RX DONE!
Bank INIT
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 0 
from app: 1 
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 1 
from app: 1 
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 2 
from app: 1 
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 3 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 1 
API_Try2Send success!
8NI_RX DONE!
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 2 
API_Try2Send failed - NI_TX occupied!
8NI_RX DONE!
TX interruption catched
API_Try2Send success!
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 3 
API_Try2Send failed - NI_TX occupied!
8NI_RX DONE!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 0 
from app: 1 
TX interruption catched
API_Try2Send success!
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 4 
API_Try2Send failed - NI_TX occupied!
8NI_RX DONE!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 3 
from app: 1 
TX interruption catched
API_Try2Send success!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 2 
from app: 1 
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 1 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 5 
API_Try2Send success!
8NI_RX DONE!
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 6 
API_Try2Send failed - NI_TX occupied!
8NI_RX DONE!
TX interruption catched
API_Try2Send success!
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 7 
API_Try2Send failed - NI_TX occupied!
8NI_RX DONE!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 2 
from app: 1 
TX interruption catched
API_Try2Send success!
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 0 
API_Try2Send failed - NI_TX occupied!
8NI_RX DONE!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 1 
from app: 1 
TX interruption catched
API_Try2Send success!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 0 
from app: 1 
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 3 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 1 
API_Try2Send success!
8NI_RX DONE!
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 2 
API_Try2Send failed - NI_TX occupied!
8NI_RX DONE!
TX interruption catched
API_Try2Send success!
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 3 
API_Try2Send failed - NI_TX occupied!
8NI_RX DONE!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 0 
from app: 1 
TX interruption catched
API_Try2Send success!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 3 
from app: 1 
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 2 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem não encontrada, adicionando ao PendingReq!
8NI_RX DONE!
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 4 
API_Try2Send success!
8NI_RX DONE!
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 5 
API_Try2Send failed - NI_TX occupied!
8NI_RX DONE!
TX interruption catched
API_Try2Send success!
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 6 
API_Try2Send failed - NI_TX occupied!
8NI_RX DONE!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 1 
from app: 1 
>>>>>Achei aqui no pending!
SendingQueue_front: 7 
API_Try2Send failed - NI_TX occupied!
TX interruption catched
API_Try2Send success!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 2 
from app: 1 
TX interruption catched
API_Try2Send success!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 0 
from app: 1 
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 1 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 0 
API_Try2Send success!
8NI_RX DONE!
TX interruption catched
API_Try2Send failed - empty SendQueue!
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 1 
API_Try2Send success!
8NI_RX DONE!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 1 
from app: 1 
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 3 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 2 
API_Try2Send success!
8NI_RX DONE!
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem não encontrada, adicionando ao PendingReq!
8NI_RX DONE!
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 3 
API_Try2Send failed - NI_TX occupied!
8NI_RX DONE!
TX interruption catched
API_Try2Send success!
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 4 
API_Try2Send failed - NI_TX occupied!
8NI_RX DONE!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 1 
from app: 1 
TX interruption catched
API_Try2Send success!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 0 
from app: 1 
>>>>>Achei aqui no pending!
SendingQueue_front: 5 
API_Try2Send failed - NI_TX occupied!
TX interruption catched
API_Try2Send success!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 2 
from app: 1 
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 0 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 6 
API_Try2Send success!
8NI_RX DONE!
TX interruption catched
API_Try2Send failed - empty SendQueue!
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 7 
API_Try2Send success!
8NI_RX DONE!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 2 
from app: 1 
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 1 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 0 
API_Try2Send success!
8NI_RX DONE!
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 1 
API_Try2Send failed - NI_TX occupied!
8NI_RX DONE!
TX interruption catched
API_Try2Send success!
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 2 
API_Try2Send failed - NI_TX occupied!
8NI_RX DONE!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 3 
from app: 1 
TX interruption catched
API_Try2Send success!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 2 
from app: 1 
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 1 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 3 
API_Try2Send success!
8NI_RX DONE!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 3 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 4 
API_Try2Send success!
8NI_RX DONE!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 0 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 5 
API_Try2Send success!
8NI_RX DONE!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 2 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 6 
API_Try2Send success!
8NI_RX DONE!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 1 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 7 
API_Try2Send success!
8NI_RX DONE!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 3 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 0 
API_Try2Send success!
8NI_RX DONE!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 0 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 1 
API_Try2Send success!
8NI_RX DONE!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 2 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 2 
API_Try2Send success!
8NI_RX DONE!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 1 
from app: 1 
dynamicEnergy_Router >> 4020486 
total instructions~~~> 1999138 
TotalEnergy: 17943372 
EnergyPckt sent
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 3 
API_Try2Send success!
8NI_RX DONE!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 3 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 4 
API_Try2Send success!
8NI_RX DONE!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 0 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 5 
API_Try2Send success!
8NI_RX DONE!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 2 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 6 
API_Try2Send success!
8NI_RX DONE!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 3 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 7 
API_Try2Send success!
8NI_RX DONE!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 0 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 0 
API_Try2Send success!
8NI_RX DONE!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 2 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 1 
API_Try2Send success!
8NI_RX DONE!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 1 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 2 
API_Try2Send success!
8NI_RX DONE!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 0 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 3 
API_Try2Send success!
8NI_RX DONE!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 2 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 4 
API_Try2Send success!
8NI_RX DONE!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 1 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 5 
API_Try2Send success!
8NI_RX DONE!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 2 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 6 
API_Try2Send success!
8NI_RX DONE!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 1 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 7 
API_Try2Send success!
8NI_RX DONE!
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 0 
API_Try2Send failed - NI_TX occupied!
8NI_RX DONE!
TX interruption catched
API_Try2Send success!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 3 
from app: 1 
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 2 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 1 
API_Try2Send success!
8NI_RX DONE!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 0 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 2 
API_Try2Send success!
8NI_RX DONE!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 3 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 3 
API_Try2Send success!
8NI_RX DONE!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 2 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 4 
API_Try2Send success!
8NI_RX DONE!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 0 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 5 
API_Try2Send success!
8NI_RX DONE!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 1 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 6 
API_Try2Send success!
8NI_RX DONE!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 2 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 7 
API_Try2Send success!
8NI_RX DONE!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 0 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 0 
API_Try2Send success!
8NI_RX DONE!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 1 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 1 
API_Try2Send success!
8NI_RX DONE!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 3 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 2 
API_Try2Send success!
8NI_RX DONE!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 0 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 3 
API_Try2Send success!
8NI_RX DONE!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 1 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 4 
API_Try2Send success!
8NI_RX DONE!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 3 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 5 
API_Try2Send success!
8NI_RX DONE!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 2 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 6 
API_Try2Send success!
8NI_RX DONE!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 1 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 7 
API_Try2Send success!
8NI_RX DONE!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 3 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 0 
API_Try2Send success!
8NI_RX DONE!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 2 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 1 
API_Try2Send success!
8NI_RX DONE!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 0 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 2 
API_Try2Send success!
8NI_RX DONE!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 3 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 3 
API_Try2Send success!
8NI_RX DONE!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 2 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 4 
API_Try2Send success!
8NI_RX DONE!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 0 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 5 
API_Try2Send success!
8NI_RX DONE!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 2 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 6 
API_Try2Send success!
8NI_RX DONE!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 0 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 7 
API_Try2Send success!
8NI_RX DONE!
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 0 
API_Try2Send failed - NI_TX occupied!
8NI_RX DONE!
TX interruption catched
API_Try2Send success!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 1 
from app: 1 
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 2 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 1 
API_Try2Send success!
8NI_RX DONE!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 3 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 2 
API_Try2Send success!
8NI_RX DONE!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 1 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 3 
API_Try2Send success!
8NI_RX DONE!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 2 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 4 
API_Try2Send success!
8NI_RX DONE!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 3 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 5 
API_Try2Send success!
8NI_RX DONE!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 0 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 6 
API_Try2Send success!
8NI_RX DONE!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 2 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 7 
API_Try2Send success!
8NI_RX DONE!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 3 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 0 
API_Try2Send success!
8NI_RX DONE!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 0 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 1 
API_Try2Send success!
8NI_RX DONE!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 1 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 2 
API_Try2Send success!
8NI_RX DONE!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 3 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 3 
API_Try2Send success!
8NI_RX DONE!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 0 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 4 
API_Try2Send success!
8NI_RX DONE!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 1 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 5 
API_Try2Send success!
8NI_RX DONE!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 2 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 6 
API_Try2Send success!
8NI_RX DONE!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 0 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 7 
API_Try2Send success!
8NI_RX DONE!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 1 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 0 
API_Try2Send success!
8NI_RX DONE!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 2 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 1 
API_Try2Send success!
8NI_RX DONE!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 3 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 2 
API_Try2Send success!
8NI_RX DONE!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 1 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 3 
API_Try2Send success!
8NI_RX DONE!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 2 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 4 
API_Try2Send success!
8NI_RX DONE!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 3 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 5 
API_Try2Send success!
8NI_RX DONE!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 0 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 6 
API_Try2Send success!
8NI_RX DONE!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 2 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 7 
API_Try2Send success!
8NI_RX DONE!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 3 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 0 
API_Try2Send success!
8NI_RX DONE!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 0 
from app: 1 
RX interruption catched
TASK_ALLOCATION_SEND
Got slot: 1 
Task total size (txt+bss): 1472 
Task addr: 2147563992 
Task slot: 1 
Task slot TaskAddr: 2147563992 
2NI_RX DONE!
RX interruption catched
TASK_ALLOCATION_FINISHED
SendingQueue_front: 1 
API_Try2Send success!
4NI_RX DONE!
TX interruption catched
API_Try2Send failed - empty SendQueue!
RX interruption catched
Chegou um TASK_START!
6NI_RX DONE!
RX interruption catched
Chegou um TASK_RUN!
Starting Task 0  from app 0 
taskSlot run: 1 
7NI_RX DONE!
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 2 
API_Try2Send success!
8NI_RX DONE!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 1 
from app: 1 
PROD1 Start 
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 3 
API_Try2Send success!
8NI_RX DONE!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 1 
Adding a msg to task 1  in the PIPE slot 3 
from app: 0 
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 4 
API_Try2Send success!
8NI_RX DONE!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 1 
Adding a msg to task 1  in the PIPE slot 0 
from app: 0 
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 5 
API_Try2Send success!
8NI_RX DONE!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 2 
from app: 1 
